name: Build and Test

on: [push, pull_request]
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.11.4
      - name: Check cairo format
        working-directory: contracts
        run: scarb fmt --check
      - name: Build cairo programs
        working-directory: contracts
        run: scarb build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.11.4
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: 0.43.0
      - name: Run cairo tests
        working-directory: contracts
        run: snforge test